/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#081425',
        surface: '#081425',
        'surface-dim': '#081425',
        'surface-bright': '#2f3a4c',
        'surface-container-lowest': '#040e1f',
        'surface-container-low': '#111c2d',
        'surface-container': '#152031',
        'surface-container-high': '#1f2a3c',
        'surface-container-highest': '#2a3548',
        'surface-variant': '#2a3548',
        'on-surface': '#d8e3fb',
        'on-surface-variant': '#c6c6cd',
        'on-background': '#d8e3fb',
        outline: '#909097',
        'outline-variant': '#45464d',
        primary: '#bec6e0',
        'on-primary': '#283044',
        'primary-container': '#0f172a',
        'on-primary-container': '#798098',
        secondary: '#4ae176',
        'on-secondary': '#003915',
        'secondary-container': '#00b954',
        'on-secondary-container': '#004119',
        tertiary: '#ffb690',
        'on-tertiary': '#552100',
        'tertiary-container': '#2d0e00',
        'on-tertiary-container': '#d45d00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        display: ['Lexend', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
